#!/usr/bin/env bash

export CONTECO_LABEL="filebeat.kafka - ContEco"
export CONTECO_DESCRIPTION="Filebeat image with Kafka input, with templated default configuration."

export CONTECO_TYPE="filebeat"
export CONTECO_NAME="kafka"
export CONTECO_TAG="7.8.0"

export CONTECO_BASE="external.filebeat:7.8.0"
export CONTECO_BUILD="image-base"
